version: "3.8"

services:
  assistants:
    container_name: assistants_container
    image: 'assistants:latest'

    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      shm_size: 512M
    ports:
      - "5000:5000"
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: "python app.py"
volumes:
  model_repository: